version: '3'
services:
  # 1. Aplikasi Laravel (PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: service-display-app
    container_name: service-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - service-network

  # 2. Web Server (Nginx)
  webserver:
    image: nginx:alpine
    container_name: service-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - service-network
    depends_on:
      - app

  # 3. Database (MySQL)
  db:
    image: mysql:8.0
    container_name: service-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - service-network

# Network & Volume definition
networks:
  service-network:
    driver: bridge

volumes:
  dbdata:
    driver: local